const balanceEl = document.getElementById('balance');
const container = document.getElementById('market-container');

let credits = parseInt(localStorage.getItem('p_credits')) || 100;
let myBets = JSON.parse(localStorage.getItem('p_bets')) || [];

async function init() {
    balanceEl.innerText = credits;
    
    // 1. Load the data generated by the AI
    const response = await fetch('data.json');
    const data = await response.json();

    // 2. Check if any of your old bets WON
    checkWinnings(data.history);

    // 3. Render current betting options
    container.innerHTML = data.current_events.map(ev => `
        <div class="event-card">
            <h4>${ev.title} <span class="payout">${ev.payout}x</span></h4>
            <p>${ev.desc}</p>
            <input type="number" id="input-${ev.id}" class="bet-input" placeholder="0">
            <button class="bet-button" onclick="placeBet('${ev.id}', ${ev.payout}, '${ev.title}')">Place Bet</button>
        </div>
    `).join('');
}

function placeBet(id, payout, title) {
    const amt = parseInt(document.getElementById(`input-${id}`).value);
    if (amt > 0 && amt <= credits) {
        credits -= amt;
        myBets.push({ id, amt, payout, title, settled: false });
        save();
        alert("Bet placed! Check back tomorrow.");
    } else {
        alert("Check your credit balance.");
    }
}

function checkWinnings(history) {
    myBets.forEach((bet, index) => {
        if (!bet.settled) {
            const result = history.find(h => h.id === bet.id);
            if (result) {
                if (result.result === "WON") {
                    const winAmt = Math.floor(bet.amt * bet.payout);
                    credits += winAmt;
                    alert(`WINNER! You won ${winAmt} on: ${bet.title}`);
                }
                bet.settled = true;
            }
        }
    });
    save();
}

function save() {
    localStorage.setItem('p_credits', credits);
    localStorage.setItem('p_bets', JSON.stringify(myBets));
    balanceEl.innerText = credits;
}

init();
